# Generated by Django 5.0.7 on 2024-07-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WATER', 'вода'), ('MAINTENANCE', 'содержание имущества')], max_length=30, verbose_name='тип тарифа')),
                ('rate', models.FloatField(verbose_name='стоимость по тарифу')),
            ],
        ),
    ]
