# Generated by Django 5.0.7 on 2024-07-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WATER', 'вода')], max_length=20, verbose_name='тип счётчика')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='building.apartment', verbose_name='счётчик')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(help_text='ММГГГГ', max_length=6, verbose_name='месяц и год')),
                ('readings', models.IntegerField(verbose_name='показания')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meter.meter', verbose_name='показания')),
            ],
        ),
    ]
