# Generated by Django 5.0.7 on 2024-07-27 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybill',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_bills', to='building.apartment', verbose_name='счёт за квартиру'),
        ),
    ]
