# Generated by Django 5.0.7 on 2024-07-28 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_alter_monthlybill_apartment'),
        ('building', '0002_alter_apartment_floor_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(help_text='ММГГГГ', max_length=6, verbose_name='месяц и год')),
                ('total_apartments', models.PositiveSmallIntegerField(verbose_name='всего квартир')),
                ('completed_apartments', models.PositiveSmallIntegerField(verbose_name='квартир обработано')),
                ('status', models.CharField(choices=[('PENDING', 'не начат'), ('IN_PROGRESS', 'в процессе'), ('COMPLETED', 'завершён'), ('FAILED', 'ошибка')], max_length=20, verbose_name='статус')),
            ],
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_bills', to='building.apartment', verbose_name='счёт за квартиру'),
        ),
        migrations.AddConstraint(
            model_name='monthlybill',
            constraint=models.UniqueConstraint(fields=('apartment', 'month_year'), name='unique_monthly_bill'),
        ),
        migrations.AddField(
            model_name='calculationprogress',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_progresses', to='building.building', verbose_name='дом'),
        ),
        migrations.AddConstraint(
            model_name='calculationprogress',
            constraint=models.UniqueConstraint(fields=('building', 'month_year'), name='unique_monthly_bill_calculation_progress'),
        ),
    ]
