# Generated by Django 5.0.7 on 2024-07-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_calculationprogress_alter_monthlybill_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationprogress',
            name='total_apartments',
        ),
        migrations.AlterField(
            model_name='calculationprogress',
            name='completed_apartments',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='квартир обработано'),
        ),
        migrations.AlterField(
            model_name='calculationprogress',
            name='status',
            field=models.CharField(choices=[('PENDING', 'не начат'), ('IN_PROGRESS', 'в процессе'), ('COMPLETED', 'завершён'), ('FAILED', 'ошибка')], default='PENDING', max_length=20, verbose_name='статус'),
        ),
    ]
